# **NUMPY -- Exercises**
## **MSc in Mathematics and Finance 2024-2025**
---
<img src="Imperial_logo.png" align = "left" width=250>
 <br><br><br> 

# 1. Exercise:


Write a piece of code to reverse a numpy array.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Answer
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


# 2. Exercise

Replace all odd values in an integer array with -1 e.g. [1, 2, 3, 4, 5, 6, 7, 8, 9] should be transofmed into [-1  2 -1  4 -1  6 -1  8 -1]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Answer
arr[arr % 2 != 0] = -1 # % is the modulo operator e.g. the reminder when dividing by 2, which is 0 when the number is even
print(arr)  # Output: [-1  2 -1  4 -1  6 -1  8 -1]

[-1  2 -1  4 -1  6 -1  8 -1]


# 3. Exercise
  Given a 2D array, find the row with the largest sum.

In [3]:
def find_max_sum_row(arr):
    """
     Args:
    arr: A 2D NumPy array of integers.

  Returns:
    A 1D array with the row with the largest sum of values
    """
    row_sums = np.sum(arr, axis=1)
    max_row_index = np.argmax(row_sums)
    return arr[max_row_index]

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Answer
find_max_sum_row(arr)

array([7, 8, 9])

# 4. Exercise
Normalize an array so that its values range between 0 and 1. 

**Hint:** Compute the maximum and minimum value to map the maximum value to 1 and the minimum value to 0




In [4]:
import numpy as np

arr = np.array([1, 5, 2, 8, 3])

# Answer
normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized_arr)  

[0.         0.57142857 0.14285714 1.         0.28571429]


# 5. Exercise

 Given a 2D integer array, sort it by a specific column.

In [5]:
def sort_by_colum(arr,col):
    """
     Args:
    arr: A 2D NumPy array of integers.
    col: column we want to sort

  Returns:
    A 2D array where the column col is sorted in increasing order.
    """
    sorted_indices = np.argsort(arr[:, col])  # Sort by column col
    return arr[sorted_indices]

# 6. Exercise

 Given a 1D array of integers, write a function using NumPy to find the two numbers that sum closest to zero.

This exercise encourages students to think about array manipulation, absolute values, and potentially sorting for an efficient solution.

In [6]:
import numpy as np

def find_closest_to_zero_sum(arr):
  """
  Finds the two numbers in an array that sum closest to zero.

  Args:
    arr: A 1D NumPy array of integers.

  Returns:
    A tuple containing the two numbers.
  """
  # Answer:
  arr = np.sort(arr)  # Sort the array
  l, r = 0, len(arr) - 1
  min_sum = np.inf
  result = (None, None)
  while l < r:
    current_sum = arr[l] + arr[r]
    if abs(current_sum) < abs(min_sum):
      min_sum = current_sum
      result = (arr[l], arr[r])
    if current_sum < 0:
      l += 1
    else:
      r -= 1
  return result


# Test the function
arr = np.array([-2, 1, -3, 4, 5, -6])
print(find_closest_to_zero_sum(arr)) 

(-6, 5)


# Exercise 7
 Implement a moving average filter with an integer window size on a 1D array.

In [7]:
import numpy as np

def moving_average(arr, window_size):
  """
  Calculates the moving average of an array.

  Args:
    arr: The input 1D NumPy array.
    window_size: The size of the moving average window.

  Returns:
    A 1D NumPy array with the moving averages.
  """
  # Answer:
  cumsum = np.cumsum(arr)
  cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]
  return cumsum[window_size - 1:] / window_size


arr = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
result = moving_average(arr, window_size)
print(result)  # Output: [2. 3. 4. 5. 6. 7. 8.]

[2. 3. 4. 5. 6. 7. 8.]
