# **Intro to Financial Computing with Numpy**
## **MSc in Mathematics and Finance 2025-2026**
---
<img src="Imperial_logo.png" align = "left" width=250>
 <br><br><br> 

# What Is Financial Computing?

**Financial computing** is the intersection of **finance**, **mathematics**, and **computer science**.  
It focuses on using computational methods, algorithms, and numerical techniques to **model, analyze, and optimize financial systems**.

> In short:  
> **Financial computing** is the use of programming, numerical analysis, and data-driven modeling to solve complex financial problems.

---

## Key Topics in Financial Computing

| Area | Description | Common Methods / Tools |
|------|--------------|------------------------|
| **Numerical Methods for Finance** | Solving pricing and risk equations computationally | Monte Carlo simulation, finite differences |
| **Portfolio Optimization** | Balancing risk and return | Linear algebra, quadratic programming |
| **Time Series & Econometrics** | Modeling and forecasting market behavior | ARIMA, GARCH, Kalman filters |
| **Machine Learning in Finance** | Using data-driven models for prediction | PCA, regression, neural networks |
| **High-Performance Computing** | Accelerating large-scale simulations | Parallel computing, GPU acceleration |
| **Financial Databases & Systems** | Managing and analyzing financial data | SQL, kdb+, time-series databases |
| **Risk Management** | Quantifying and mitigating financial risk | Value-at-Risk (VaR), stress testing |
| **Algorithmic & Quantitative Trading** | Automating trading decisions | Backtesting, optimization, execution systems |

---

## Example Problems Solved with Financial Computing

1. **Option Pricing**  
   Estimate the fair value of derivatives using Monte Carlo or finite difference methods.

2. **Portfolio Optimization**  
   Use linear algebra to find the optimal portfolio weights that minimize variance for a target return.

3. **Risk Simulation**  
   Model thousands of market scenarios to estimate Value at Risk (VaR) or Expected Shortfall.

4. **Factor Modeling**  
   Apply PCA to uncover common factors driving asset returns.

5. **Algorithmic Trading**  
   Implement automated trading strategies that react to real-time market data.

---



## Career Paths

| Role | Description |
|------|--------------|
| **Quantitative Analyst ("Quant")** | Develops pricing and risk models using mathematics and code |
| **Algorithmic Trader / Quant Trader** | Designs and implements automated trading strategies |
| **Quant Developer** | Implements and maintains quantitative libraries with strong focus in efficiency |
| **Risk Modeler** | Simulates financial scenarios to estimate exposure |
| **Financial Data Scientist** | Uses ML and data analysis for forecasting and insights |
| **Software Engineer (Finance / FinTech)** | Builds large-scale trading, analytics, or risk systems |

---



### An example with Numpy: Principal Component Analysis (PCA)

PCA is not only a practical tool for dimensionality reduction but also a mathematically elegant transformation with powerful properties.

Let’s recall the core idea:

Given a dataset $X=(X_1,...,X_N) \in \mathbb{R}^{T \times N} $, where each column $X_i\in\mathbb{R}^T$ is a **standardized variable** (e.g. $\mathbb{E}[X_i]=0$ and $\mathbb{V}[X]=1$)

1. Compute the sample covariance matrix:
   $
   \Sigma = \frac{1}{T-1} X^\top X 
   $ **Note:** this holds due to $\mathbb{E}[X_i]=0$
2. Find its eigenvalues and eigenvectors:
   $
   \Sigma v_i = \lambda_i v_i
   $
3. The eigenvectors $ v_i $ form an **orthogonal basis**, and the eigenvalues $ \lambda_i $ measure the variance explained by each component.

The transformation into principal components is:

$
Z = X V
$

where $ V = [v_1, v_2, \dots, v_N] $ is the eigenvector matrix.


In [12]:
import numpy as np
# define number of assets an number of observations to be used
np.random.seed(0)
n_assets = 6
n_obs = 300


#### Next we construct a simmetric unit covariance matrix we can sample from. To do so, we use tha fact that given any square matrix $A$, we have that $B=AA^T$ is simmetric and $\Sigma=D^{-1}BD^{-1}$ is a valid correlation matrix i.e. represents a valid unit variance random vector. $D$ is a diagonal matrix where $Diag(D)=\sqrt{Diag(\Sigma)}$

In [28]:
A = np.random.randn(n_assets, n_assets)

B = A @ A.T
D_inverse=np.zeros((n_assets,n_assets))
np.fill_diagonal(D_inverse,1.0/np.sqrt(np.diag(B)))


In [14]:
corr_matrix=D_inverse@B@D_inverse

In [15]:
corr_matrix

array([[ 1.00000000e+00,  1.92492797e-01,  8.43602845e-01,
         1.36037434e-01,  3.51757759e-01, -6.85435416e-01],
       [ 1.92492797e-01,  1.00000000e+00,  2.22128486e-01,
         7.03232326e-04,  7.52011378e-01, -1.12625668e-01],
       [ 8.43602845e-01,  2.22128486e-01,  1.00000000e+00,
         1.23521175e-01,  5.70852956e-01, -3.61183607e-01],
       [ 1.36037434e-01,  7.03232326e-04,  1.23521175e-01,
         1.00000000e+00,  1.88198837e-01,  4.15599665e-02],
       [ 3.51757759e-01,  7.52011378e-01,  5.70852956e-01,
         1.88198837e-01,  1.00000000e+00, -2.22856363e-02],
       [-6.85435416e-01, -1.12625668e-01, -3.61183607e-01,
         4.15599665e-02, -2.22856363e-02,  1.00000000e+00]])

#### Now we are able to sample data from a standardized covariance matrix and compute eigenvalues and eigenvectors using linear algebra in numpy

In [16]:
X = np.random.multivariate_normal(np.zeros(n_assets), corr_matrix, size=n_obs)

# Sample Covariance and eigendecomposition. We don't center the sample since we know it has mean zero.
Sigma = np.cov(X, rowvar=False)
eigvals, eigvecs = np.linalg.eig(Sigma)
idx = np.argsort(eigvals)[::-1] ## we sort eigenvalues
eigvals, eigvecs = eigvals[idx], eigvecs[:, idx]## reorganize eigenvalues and vectors from largest to smallest

# Project data
Z = X @ eigvecs


In [19]:
eigvals

array([2.54597624, 1.6226915 , 0.93010472, 0.57740585, 0.14059149,
       0.03915131])

In [20]:
eigvecs

array([[ 0.53225614,  0.33277084,  0.08866611,  0.06705293,  0.41924322,
        -0.64640878],
       [ 0.31755765, -0.43771811, -0.41144659, -0.49261712,  0.48596914,
         0.24379103],
       [ 0.54375882,  0.10067697,  0.06259671,  0.5663007 ,  0.05886629,
         0.6050706 ],
       [ 0.15787338, -0.33348731,  0.88512773, -0.27188807,  0.03350204,
         0.07325034],
       [ 0.43398327, -0.51376525, -0.18608315,  0.11074976, -0.62712354,
        -0.32791371],
       [-0.32698839, -0.5588936 ,  0.02921729,  0.58817273,  0.43611644,
        -0.20908892]])

In [21]:
Z

array([[-2.04672864,  1.47990066,  0.06557973, -0.16054987, -0.41075018,
        -0.30959489],
       [ 2.80756332,  2.40149272, -0.05829031, -0.32386218, -0.52398012,
         0.13610122],
       [ 2.62166476, -0.0368768 , -1.09668498,  0.17547574, -0.19718017,
        -0.25197741],
       ...,
       [ 2.09965931, -0.73675937, -1.0672616 , -0.36559628,  0.29107504,
        -0.04524205],
       [ 1.51409323, -1.68179175, -0.45673445, -0.08673606,  0.58090747,
         0.03346729],
       [ 0.12991791, -1.14627781, -0.576083  , -0.41559677, -0.14591403,
        -0.17340011]], shape=(300, 6))

## Orthogonality of Principal Components

One of the key properties of PCA is that the **principal components are orthogonal**.

This means:
$
v_i^\top v_j = 0 \quad \text{for } i \neq j
$
and consequently, their scores (columns of $Z $) are **uncorrelated**.


In [23]:
# Check orthogonality of eigenvectors
orthogonality_matrix = eigvecs.T @ eigvecs
print("Eigenvector dot products (should be close to identity):\n", orthogonality_matrix)

# Check correlation among principal component scores
corr_Z = np.corrcoef(Z.T)
print("\nCorrelation matrix of principal components (should be close to diagonal):\n", corr_Z)


Eigenvector dot products (should be close to identity):
 [[ 1.00000000e+00 -2.97951823e-16 -2.20679960e-16 -2.84413326e-16
  -3.15186944e-16 -5.93091998e-16]
 [-2.97951823e-16  1.00000000e+00 -8.56681178e-17  1.19399128e-16
   8.72997566e-17  5.07834081e-16]
 [-2.20679960e-16 -8.56681178e-17  1.00000000e+00  5.60504253e-16
  -7.14812048e-16 -1.96099858e-17]
 [-2.84413326e-16  1.19399128e-16  5.60504253e-16  1.00000000e+00
   6.04311151e-16 -4.59662361e-16]
 [-3.15186944e-16  8.72997566e-17 -7.14812048e-16  6.04311151e-16
   1.00000000e+00 -4.35974571e-17]
 [-5.93091998e-16  5.07834081e-16 -1.96099858e-17 -4.59662361e-16
  -4.35974571e-17  1.00000000e+00]]

Correlation matrix of principal components (should be close to diagonal):
 [[ 1.00000000e+00 -8.03059904e-17  1.49635758e-17 -2.36965101e-17
  -1.06710883e-15 -1.71948943e-15]
 [-8.03059904e-17  1.00000000e+00 -2.43157667e-16 -6.69881955e-17
  -8.00936178e-16  2.18633138e-15]
 [ 1.49635758e-17 -2.43157667e-16  1.00000000e+00  9.47151

### Observations

- The eigenvectors are orthogonal → $ V^\top V = I $.
- The principal components $ Z = XV $ are *uncorrelated* random variables — this is evident from the nearly diagonal correlation matrix.

This is what allows PCA to **decorrelate** correlated financial assets.


##  Visualizing Variance Explained

Let's visualize the **cumulative explained variance** to see how many components are needed to explain most of the total variability. To see this we just need to compare individual eigenvalues of components against the sum of all eigenvalues

In [24]:
explained_var_ratio = eigvals / eigvals.sum()
cum_var = np.cumsum(explained_var_ratio)



In [26]:
explained_var_ratio

array([0.43476956, 0.27710269, 0.1588315 , 0.09860205, 0.02400843,
       0.00668577])

In [27]:
cum_var

array([0.43476956, 0.71187225, 0.87070375, 0.9693058 , 0.99331423,
       1.        ])

### Q? Can we use PCA if the observations are not Gaussian?

# When Is PCA Optimal, and How Does Non-Gaussianity Affect It?

## 1. Optimality of PCA

Principal Component Analysis (PCA) finds an **orthogonal linear transformation** that captures the maximum possible variance in the smallest number of components.

Formally, given zero-mean data $ X \in \mathbb{R}^{T \times N} $:

$
\Sigma = \frac{1}{T-1} X^\top X
$

PCA solves recursively:
$\mathbf{w}_{(1)} = \arg\max \left\{ \frac{\mathbf{w}^\mathsf{T} \mathbf{X}^\mathsf{T} \mathbf{X w}}{\mathbf{w}^\mathsf{T} \mathbf{w}} \right\}$


The first principal component $w_1$ is the direction of **maximum variance**.  
Each subsequent component is orthogonal to the previous ones and captures the next-largest share of variance.
The k-th component can be found by subtracting the first k-1 principal components from $X$:

$\mathbf{\hat{X}}_k = \mathbf{X} - \sum_{s = 1}^{k - 1} \mathbf{X} \mathbf{w}_{(s)} \mathbf{w}_{(s)}^{\mathsf{T}} $

and then finding the weight vector which extracts the maximum variance from this new data matrix

$\mathbf{w}_{(k)}
= \mathop{\operatorname{arg\,max}}_{\left\| \mathbf{w} \right\| = 1} \left\{ \left\| \mathbf{\hat{X}}_{k} \mathbf{w} \right\|^2 \right\}
= \arg\max \left\{ \tfrac{\mathbf{w}^\mathsf{T} \mathbf{\hat{X}}_{k}^\mathsf{T} \mathbf{\hat{X}}_{k} \mathbf{w}}{\mathbf{w}^T \mathbf{w}} \right\}$


#### Lucky for us, this boils down to finding eigenvalues and eigenvectors
---


## 2. When Data Are Non-Gaussian

In practice, **financial data are rarely Gaussian**:
- They often exhibit **heavy tails** (kurtosis > 3)
- **Skewness**
- **Volatility clustering**
- **Nonlinear dependencies**

In these cases:

1. **Uncorrelated ≠ Independent**

   PCA only ensures that the transformed variables are *uncorrelated*:
   $
   \text{Cov}(Z_i, Z_j) = 0 \quad (i \ne j)
   $
   But for non-Gaussian data, they may still exhibit *higher-order* dependencies (nonlinear relationships).

2. **PCA is not statistically optimal**

   PCA minimizes *mean squared reconstruction error*, but not necessarily the true *information loss*.  
   For non-Gaussian data, other directions may better separate structure or "independent" components.

3. **Principal components may not correspond to true sources**

   If your data were generated by mixing several latent independent signals (e.g., in financial factor models), PCA won’t necessarily recover those sources.  
   Instead, methods like **Independent Component Analysis (ICA)** can separate them more effectively.

---

## 3. Financial Implications

Financial returns are often **non-Gaussian**:
- Fat-tailed (extreme events are more likely)
- Asymmetric
- Sometimes exhibit **nonlinear dependencies** across assets

This means:
- PCA can still be used as a **decorrelation** or **dimension-reduction** tool,  
  but its components may not correspond to *true independent market factors*.
- The first few components (especially the first one) still often capture the *market-wide risk* due to large common variance.
- However, later components may mix nonlinear or tail behaviors not captured by simple covariance structure.

---

